# Generated by Django 2.0.8 on 2018-12-08 03:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carelineapp', '0011_auto_20181203_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_ref', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadDB',
            fields=[
                ('tracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='leads.Tracking')),
                ('leadid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_contact_name', models.CharField(max_length=250, null=True)),
                ('recipient_contact_number', models.CharField(max_length=20)),
                ('referral_text_message_reason', models.CharField(max_length=255, null=True)),
                ('date_time_referral', models.DateTimeField(null=True)),
                ('text_message_body', models.CharField(max_length=1000, null=True)),
                ('callback_permission', models.BooleanField(default=False)),
                ('recipient_permission', models.BooleanField(default=False)),
                ('bitly_link', models.CharField(blank=True, max_length=100, null=True)),
                ('bitly_link_clicked', models.BooleanField(default=False)),
                ('twilio_sms_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('careline_topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='carelineapp.Topic')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Lead Analytics',
            },
            bases=('leads.tracking',),
        ),
    ]
