# Generated by Django 2.0.8 on 2019-03-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leaddb_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddb',
            name='bitly_link',
            field=models.CharField(blank=True, default='https://ccareline.app/#', max_length=100, null=True),
        ),
    ]
