# Generated by Django 2.0.8 on 2018-10-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_id',
            field=models.IntegerField(default=1, help_text='Topic ID'),
            preserve_default=False,
        ),
    ]
