# Generated by Django 2.0.8 on 2018-11-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carelineapp', '0003_auto_20181029_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddresssettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='googlesettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='CompanyAddressSettings',
        ),
        migrations.DeleteModel(
            name='GoogleSettings',
        ),
    ]
