# Generated by Django 2.0.8 on 2018-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelineapp', '0004_auto_20181103_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='text',
            field=models.CharField(help_text='Add {{topic_title}} for Name of Service and {{name}} for Name of recipient /and {{link}} for the service pdf bitly link', max_length=160),
        ),
    ]
