# Generated by Django 2.0.8 on 2018-11-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carelineapp', '0008_auto_20181119_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='counselling_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
