# Generated by Django 2.0.8 on 2018-11-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelineapp', '0009_auto_20181119_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(help_text='Title of counselling topic', max_length=65),
        ),
    ]
