# Generated by Django 2.0.8 on 2018-12-03 03:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carelineapp', '0010_auto_20181119_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuppage',
            name='organisation_helper_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signuppage',
            name='postcode_helper_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
