# Generated by Django 2.0.8 on 2019-03-18 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carelineapp', '0011_auto_20181203_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='counselling_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
