# Generated by Django 2.0.8 on 2018-12-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scarface', '0004_auto_20151217_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=110)),
                ('device', models.ManyToManyField(to='scarface.Device')),
            ],
        ),
    ]
