# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0035_auto_20171218_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='draft_title',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
